$(document).ready(function(){
    $("#text2").hide();
    $("#text3").hide();
    $("#text4").hide();
    $("#text5").hide();
    $("#text6").hide();
    $("#text7").hide();
    $("#text8").hide();
    $("#text9").hide();
    $("#text10").hide();
    $("#text11").hide();
    $("#text12").hide();
    $("#text13").hide();
    $("#text14").hide();
    $("#text15").hide();
    $("#text16").hide();
    $("#text17").hide();
    $("#text18").hide();
    $("#text19").hide();
    $("#text20").hide();
    $("#text20").hide();
    $("#text21").hide();
    $("#text22").hide();
    $("#text23").hide();
    $("#text24").hide();
    $("#text25").hide();
    $("#text26").hide();
    $("#text27").hide();
    $("#text28").hide();
    $("#text29").hide();
    $("#text30").hide();
    $("#text31").hide();
    $("#text32").hide();
    $("#text33").hide();
    $("#text34").hide();
    $("#text35").hide();
    $("#text1-reverse").hide();
    $("#text2-reverse").hide();
    $("#text3-reverse").hide();
    $("#text4-reverse").hide();
    $("#text5-reverse").hide();
    $("#text6-reverse").hide();
    $("#text7-reverse").hide();
    $("#text8-reverse").hide();
    $("#text9-reverse").hide();
    $("#text10-reverse").hide();
    $("#text11-reverse").hide();
    $("#text12-reverse").hide();
    $("#text13-reverse").hide();
    $("#text14-reverse").hide();
    $("#text15-reverse").hide();
    $("#text16-reverse").hide();
    $("#text17-reverse").hide();
    $("#text18-reverse").hide();
    $("#text19-reverse").hide();
    $("#text20-reverse").hide();
    $("#text20-reverse").hide();
    $("#text21-reverse").hide();
    $("#text22-reverse").hide();
    $("#text23-reverse").hide();
    $("#text24-reverse").hide();
    $("#text25-reverse").hide();
    $("#text26-reverse").hide();
    $("#text27-reverse").hide();
    $("#text28-reverse").hide();
    $("#text29-reverse").hide();
    $("#text30-reverse").hide();
    $("#text31-reverse").hide();
    $("#text32-reverse").hide();
    $("#text33-reverse").hide();
    $("#text34-reverse").hide();
    $("#text35-reverse").hide();
    $("#text1").click(function(){
        $("#text1").hide();
        $("#text2").show();
    });
    $("#text2").click(function(){
        $("#text2").hide();
        $("#text3").show();
      });
      $("#text3").click(function(){
        $("#text3").hide();
        $("#text4").show();
      });
      $("#text4").click(function(){
        $("#text4").hide();
        $("#text5").show();
      });
      $("#text5").click(function(){
        $("#text5").hide();
        $("#text6").show();
      });
      $("#text6").click(function(){
        $("#text6").hide();
        $("#text7").show();
      });
      $("#text7").click(function(){
        $("#text7").hide();
        $("#text8").show();
      });
      $("#text8").click(function(){
        $("#text8").hide();
        $("#text9").show();
      });
      $("#text9").click(function(){
        $("#text9").hide();
        $("#text10").show();
      });
      $("#text10").click(function(){
        $("#text10").hide();
        $("#text11").show();
      });
      $("#text11").click(function(){
        $("#text11").hide();
        $("#text12").show();
      });
      $("#text12").click(function(){
        $("#text12").hide();
        $("#text13").show();
      });
      $("#text13").click(function(){
        $("#text13").hide();
        $("#text14").show();
      });
      $("#text14").click(function(){
        $("#text14").hide();
        $("#text15").show();
      });
      $("#text15").click(function(){
        $("#text15").hide();
        $("#text16").show();
      });
      $("#text16").click(function(){
        $("#text16").hide();
        $("#text17").show();
      });
      $("#text17").click(function(){
        $("#text17").hide();
        $("#text18").show();
      });
      $("#text18").click(function(){
        $("#text18").hide();
        $("#text19").show();
      });
      $("#text19").click(function(){
        $("#text19").hide();
        $("#text20").show();
      });
      $("#text20").click(function(){
        $("#text20").hide();
        $("#text21").show();
      });
      $("#text21").click(function(){
        $("#text21").hide();
        $("#text22").show();
      });
      $("#text22").click(function(){
        $("#text22").hide();
        $("#text23").show();
      });
      $("#text23").click(function(){
        $("#text23").hide();
        $("#text24").show();
      });
      $("#text24").click(function(){
        $("#text24").hide();
        $("#text25").show();
      });
      $("#text25").click(function(){
        $("#text25").hide();
        $("#text26").show();
      });
      $("#text26").click(function(){
        $("#text26").hide();
        $("#text27").show();
      });
      $("#text27").click(function(){
        $("#text27").hide();
        $("#text28").show();
      });
      $("#text28").click(function(){
        $("#text28").hide();
        $("#text29").show();
      });
      $("#text29").click(function(){
        $("#text29").hide();
        $("#text30").show();
      });
      $("#text30").click(function(){
        $("#text30").hide();
        $("#text31").show();
      });
      $("#text31").click(function(){
        $("#text31").hide();
        $("#text32").show();
      });
      $("#text32").click(function(){
        $("#text32").hide();
        $("#text33").show();
      });
      $("#text33").click(function(){
        $("#text33").hide();
        $("#text34").show();
      });
      $("#text34").click(function(){
        $("#text34").hide();
        $("#text35").show();
      });
      $("#text35").click(function(){
        $("#text35").hide();
        $("#text34-reverse").show();
      });
      $("#text34-reverse").click(function(){
        $("#text34-reverse").hide();
        $("#text33-reverse").show();
      });
      $("#text33-reverse").click(function(){
        $("#text33-reverse").hide();
        $("#text32-reverse").show();
      });
      $("#text32-reverse").click(function(){
        $("#text32-reverse").hide();
        $("#text31-reverse").show();
      });
      $("#text31-reverse").click(function(){
        $("#text31-reverse").hide();
        $("#text30-reverse").show();
      });
      $("#text30-reverse").click(function(){
        $("#text30-reverse").hide();
        $("#text29-reverse").show();
      });
      $("#text29-reverse").click(function(){
        $("#text29-reverse").hide();
        $("#text28-reverse").show();
      });
      $("#text28-reverse").click(function(){
        $("#text28-reverse").hide();
        $("#text27-reverse").show();
      });
      $("#text27-reverse").click(function(){
        $("#text27-reverse").hide();
        $("#text26-reverse").show();
      });
      $("#text26-reverse").click(function(){
        $("#text26-reverse").hide();
        $("#text25-reverse").show();
      });
      $("#text25-reverse").click(function(){
        $("#text25-reverse").hide();
        $("#text24-reverse").show();
      });
      $("#text24-reverse").click(function(){
        $("#text24-reverse").hide();
        $("#text23-reverse").show();
      });
      $("#text23-reverse").click(function(){
        $("#text23-reverse").hide();
        $("#text22-reverse").show();
      });
      $("#text22-reverse").click(function(){
        $("#text22-reverse").hide();
        $("#text21-reverse").show();
      });
      $("#text21-reverse").click(function(){
        $("#text21-reverse").hide();
        $("#text20-reverse").show();
      });
      $("#text20-reverse").click(function(){
        $("#text20-reverse").hide();
        $("#text19-reverse").show();
      });
      $("#text19-reverse").click(function(){
        $("#text19-reverse").hide();
        $("#text18-reverse").show();
      });
      $("#text18-reverse").click(function(){
        $("#text18-reverse").hide();
        $("#text17-reverse").show();
      });
      $("#text17-reverse").click(function(){
        $("#text17-reverse").hide();
        $("#text16-reverse").show();
      });
      $("#text16-reverse").click(function(){
        $("#text16-reverse").hide();
        $("#text15-reverse").show();
      });
      $("#text15-reverse").click(function(){
        $("#text15-reverse").hide();
        $("#text14-reverse").show();
      });
      $("#text14-reverse").click(function(){
        $("#text14-reverse").hide();
        $("#text13-reverse").show();
      });
      $("#text13-reverse").click(function(){
        $("#text13-reverse").hide();
        $("#text12-reverse").show();
      });
      $("#text12-reverse").click(function(){
        $("#text12-reverse").hide();
        $("#text11-reverse").show();
      });
      $("#text11-reverse").click(function(){
        $("#text11-reverse").hide();
        $("#text10-reverse").show();
      });
      $("#text10-reverse").click(function(){
        $("#text10-reverse").hide();
        $("#text9-reverse").show();
      });
      $("#text9-reverse").click(function(){
        $("#text9-reverse").hide();
        $("#text8-reverse").show();
      });
      $("#text8-reverse").click(function(){
        $("#text8-reverse").hide();
        $("#text7-reverse").show();
      });
      $("#text7-reverse").click(function(){
        $("#text7-reverse").hide();
        $("#text6-reverse").show();
      });
      $("#text6-reverse").click(function(){
        $("#text6-reverse").hide();
        $("#text5-reverse").show();
      });
      $("#text5-reverse").click(function(){
        $("#text5-reverse").hide();
        $("#text4-reverse").show();
      });
      $("#text4-reverse").click(function(){
        $("#text4-reverse").hide();
        $("#text3-reverse").show();
      });
      $("#text3-reverse").click(function(){
        $("#text3-reverse").hide();
        $("#text2-reverse").show();
      });
      $("#text2-reverse").click(function(){
        $("#text2-reverse").hide();
        $("#text1-reverse").show();
      });
      $("#text1-reverse").click(function(){
        $("#text1-reverse").hide();
        $("#text1").show();
      });
  })  


  